spring:
  application:
    name: todo-app-mstg
  datasource:
    url: ${DATASOURCE-URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
#    url: jdbc:postgresql://localhost:5400/TODO-DB
#    username: user
#    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8098


